FROM ubuntu:14.04
MAINTAINER Victor Garcia <coatl@inboxalias.com>
ADD base-software prepare/base-software
RUN prepare/base-software/initialSoftwareSetup
#ADD installJavaTools prepare/installJavaTools
#ADD runInitialGitConfiguration prepare/runInitialGitConfiguration
