#!/usr/bin/env bash
#you need to execute this as root, or sudo
apt-get update
apt-get install -y software-properties-common
apt-get install -y python-software-properties
apt-get install -y git
apt-get install -y default-jdk
apt-get install -y maven
add-apt-repository ppa:webupd8team/java
apt-get update
