#!/usr/bin/env bash
#you need to execute this as root, or sudo
cat << "EOF"
╔═╗┌─┐┌┐┌┌─┐┬┌─┐┬ ┬┬─┐┬┌┐┌┌─┐  ┌─┐┌─┐┌─┐┌┬┐┬ ┬┌─┐┬─┐┌─┐
║  │ ││││├┤ ││ ┬│ │├┬┘│││││ ┬  └─┐│ │├┤  │ │││├─┤├┬┘├┤ 
╚═╝└─┘┘└┘└  ┴└─┘└─┘┴└─┴┘└┘└─┘  └─┘└─┘└   ┴ └┴┘┴ ┴┴└─└─┘
EOF
#install base software
apt-get update && apt-get install -y software-properties-common \
    python-software-properties \
    git
