#!/usr/bin/env bash
#dockerfile language specification from: https://github.com/ilogue/docker.lang.git
#Please sudo!!
#all files will be temporarily copied to relative based directories
GIT_REPO=https://github.com/ilogue/docker.lang.git
TEMP_DIR=`uuidgen`
mkdir $TEMP_DIR
git clone $GIT_REPO $TEMP_DIR
cp $TEMP_DIR/docker.lang /usr/share/gtksourceview-3.0/language-specs/
rm -rf $TEMP_DIR
