#!/usr/bin/env bash
#please sudo
GIT_REPO=https://github.com/esbeto/Lethe.git
TEMP_DIR=`uuidgen`
mkdir $TEMP_DIR
git clone $GIT_REPO $TEMP_DIR
cp -f $TEMP_DIR/*.xml /usr/share/gtksourceview-3.0/styles/
rm -rf $TEMP_DIR
