#!/usr/bin/env bash
#will install the java tools that ubuntu 
#provide by default
#
#So likely, it's going to be open JDK
#and the current maven version
#for more precise versioning
#more work is needed.. see installJava8FromOracleUsingPPA
apt-get update && apt-get install -y \
    default-jdk \ #this installs open JDK
    maven \
    gradle
