#!/usr/bin/env bash
#this accepts the license, so that
#the installation can happen silently
#
echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
add-apt-repository -y ppa:webupd8team/java && apt-get update
sudo apt-get install -y oracle-java8-installer
