FROM ubuntu:14.04
MAINTAINER Victor Garcia <coatl@inboxalias.com>
ADD initialSoftwareSetup prepare/initialSoftwareSetup
ADD installJavaTools prepare/installJavaTools
ADD runInitialGitConfiguration prepare/runInitialGitConfiguration
